#-------------------------------
# General Site Settings
baseURL = "https://www.seosaurus.fr/"
languageCode = "fr-fr"
title = "Seosaurus"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 5


[params]
logo = "" # You can add own logo. For example "/images/tlem_logo.png".
description = "SEOsaurus, webmarketing consulting."
color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Main Menu
[menu]
[[menu.main]]
name = "Accueil"
url = ""
weight = 1

[[menu.main]]
name = "Mes services"
url = "/messervices/"
weight = 2
hasChildren = true

[[menu.main]]
parent = "Mes services"
name = "Référencement SEO"
url = "/messervices/referencementseo/"
weight = 1
hasChildren = true

[[menu.main]]
parent = "Mes services"
name = "Stratégie de communication"
url = "/messervices/strategiedecommunication/"
weight = 1

[[menu.main]]
parent = "Mes services"
name = "Création de contenu (prints)"
url = "/messervices/creationdecontenu/"
weight = 2

[[menu.main]]
parent = "Mes services"
name = "Community management"
url = "/messervices/communitymanagement/"
weight = 3

[[menu.main]]
name = "Réalisations"
url = "/works/"
weight = 3

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5


#-------------------------------
# Author Settings
[params.author]
author__name = "Noah Sturtzer"
author__bio = "Ici, l'innovation rencontre la stratégie pour propulser votre marque vers des horizons inexplorés. Prêt pour une transformation digitale durable ?"
author__avatar = "/images/logo-image-400.png" #400x400

# Social Links
[[params.social]]
icon = "ion-logo-linkedin"
name = "LinkedIn"
link = "https://www.linkedin.com/in/noahsturtzer/"

[[params.social]]
icon = "ion-logo-facebook"
name = "Facebook"
link = "https://www.facebook.com/profile.php?id=61556572263770"

[[params.social]]
icon = "ion-logo-instagram"
name = "Instagram"
link = "https://www.instagram.com/seosaurus_webmarketing/"

[[params.social]]
icon = "ion-logo-github"
name = "Github"
link = "https://github.com/Thaalmor2804"

# Example of adding a new link to the footer:
# [[params.social]]
#   icon = "ion-logo-youtube"
#   name = "Youtube"
#   link = "https://youtube.com"

# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
[params.hero]
enable = true
hero__title = "Un marketing qui fuse pour une présence en ligne qui ne s'éteint jamais !"
hero__description = "Ici Noah, à votre service pour faire de votre marque le T-Rex de son domaine. Pas de long discours, juste des stratégies concrètes et des contenus percutants. Que ce soit pour définir votre stratégie sur les réseaux sociaux ou créer des contenus SEO qui captent l'attention, je m'assure que votre marque se démarque."
hero__image = "/images/noahsturtzer-photo-homepage.jpg"


#-------------------------------
# Logos Settings
[params.logos]
enable = false
logos__title = "J'ai travaillé avec de chouettes entreprises !"

[[params.logo_item]]
name = "Webvert"
link = "https://www.lewebvert.fr/"
image = "/images/logo/logo-webvert-entier.png"

[[params.logo_item]]
name = "New Art Coffee"
link = "https://www.facebook.com/profile.php?id=61550863513934/"
image = "/images/logo/logo-nac.png"

[[params.logo_item]]
name = "Socitety"
link = "https://society-rouen.fr/"
image = "/images/logo/logo-society.png"

[[params.logo_item]]
name = "Qo Creator"
link = "https://qocreators.com/"
image = "/images/logo/logo-qocreators.png"


#-------------------------------
# Newsletter Settings
[params.mailchimp]
enable = false
mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text = "Your email address..."
mailchimp__button__text = "Subscribe" # Add your button text


#-------------------------------
# Mes services



#-------------------------------
# Work Settings
[params.work]
enable = true
work__title= "Réalisations"
work__description= "Explorez mon portefolio pour voir comment on peut propulser ensemble votre projet vers de nouveaux sommets !"


#-------------------------------
# Testimonials Section
[params.testimonials]
enable = true
testimonial__title = "Clients"
testimonial__description = ""

[[params.testimonial_item]]
name = "TlemCloud"
image = "images/tlem_logo.png"
designation = "Infrastructure Serrvices"
link = "https://cloud.tlem.be/"
content = "Un grand merci à SeoSaurus pour leur expertise en SEO. Leur travail a considérablement renforcé notre présence en ligne chez TlemCloud. Professionnels et efficaces, nous recommandons vivement leurs services."

[[params.testimonial_item]]
name = "Society - Bar à jeux"
image = "/images/logo/logo-society.png"
designation = "Bar restaurant à Rouen"
link = "https://www.facebook.com/profile.php?id=61551876037556"
content = "Tro bi1"

[[params.testimonial_item]]
name = "Webvert"
image = "/images/logo/logo-webvert.png"
designation = "Décarbonation et Réparation de sites web"
link = "https://www.lewebvert.fr/"
content = "text text text"

[[params.testimonial_item]]
name = "Qo Creators"
image = "/images/logo/logo-qocreators.png"
designation = "Product industrialization"
link = "https://qocreators.com/"
content = "text text text"

[[params.testimonial_item]]
name = "New Art Coffee"
image = "/images/logo/logo-nac.png"
designation = "Torréfacteur artisanal de café"
link = "https://www.facebook.com/profile.php?id=61550863513934"
content = "text text text"


#-------------------------------
# Blog Section
[params.blog]
enable = false
blog__title = "Writing"
blog__description = ""


#-------------------------------
# Footer Settings
[params.footer]
footer__background__image = "https://via.placeholder.com/1920x1080"


#-------------------------------
# Contact Settings
[params.contact]
contact__email = "xzbnrypa" # Add your form_id

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
[params.disqus]
enable = false
disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = false
